name: Logger64
version: ${project.version}
description: This plugin logs players' connection info
author: tbm00
main: dev.tbm00.spigot.logger64.Logger64
api-version: 1.17
softdepend: [AuthMe, FastLogin]
commands:
  logger:
    description: Logger64 base command
permissions:
  logger64.admin:
    description: Ability to use table commands
    default: op
  logger64.seen:
    description: Ability to use seen command
    default: op